### ISSUE TITLE
A little personal advice

### ISSUE THREAD

**Issue by cosmicethics** [hkmix/vscode-solarized-dark-vim#1]
I have been looking for an eye protection theme, solarized is a good choice, so I have  tried a lot of solarized based themes in vscode, but they have more or less problems for me.
Until I found out the theme of your design , everything changed for the better, it is elegant and minimalist, I like it so much.
Sorry, I can't help but want to make a request, I think there is a slight flaw:
1. the ansiWhite color "#eee8d5" is much, it could be replaced by darker colors or some colors like blue and green.
2. the default cursor color is red, I changed it.
 //"editorCursor.foreground": "#dc322f",
 //"editorCursor.background": "#839496",
 change to:
 "editorCursor.foreground": "#839496",
 "editorCursor.background": "#002b36"

**Comment by hkmix** [comment]
Hi there, thanks for the feedback! That's a good idea, I'll look into adjusting stronger colours or adding a theme that avoids bold colours sometime soon.

**Comment by hkmix** [comment]
I've updated the cursor colours to use `93a1a1` and `002b36` which should reduce contrast quite a bit while retaining a bit of pop so it's easy to see the cursor. I've kept the ansiWhite colour the same for now because that's the colour code provided by the Solarized definition here: https://ethanschoonover.com/solarized/.

**Comment by hkmix** [comment]
Will resolve for now, please let me know if you need anything else!

**Comment by cosmicethics** [comment]
it's ok.
